CREATE TABLE USERS (
    USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(128) NOT NULL UNIQUE,
    PASSWORD VARCHAR(256) NOT NULL,
    ROLE ENUM ('USER', 'ADMIN')
    );

CREATE TABLE LOCATIONS (
    LOCATION_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(128) NOT NULL UNIQUE
    );

CREATE TABLE EXHIBITIONS (
    EXHIBITION_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    THEME VARCHAR(256) NOT NULL UNIQUE,
    START_OF_OPERATION DATE NOT NULL,
    END_OF_OPERATION DATE NOT NULL,
    WORKING_START TIME NOT NULL,
    WORKING_END TIME NOT NULL,
    TICKET_PRICE DECIMAL(10,2) NOT NULL
    );

CREATE TABLE EXHIBITIONS_LOCATIONS (
    EXHIBITION_ID INTEGER NOT NULL,
    LOCATION_ID INTEGER NOT NULL,
    FOREIGN KEY (EXHIBITION_ID) REFERENCES EXHIBITIONS(EXHIBITION_ID) ON DELETE CASCADE,
    FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID)
    );

CREATE TABLE ORDERS (
    ORDER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    EXHIBITION_ID INTEGER NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (EXHIBITION_ID) REFERENCES EXHIBITIONS(EXHIBITION_ID)
    );
